FROM registry.access.redhat.com/ubi9/python-39

ENV FLASK_APP="api.py"

COPY src /app
COPY requirements.txt /app

WORKDIR /app

RUN pip install -r requirements.txt

EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0"]
